# Generated by Django 5.2.4 on 2025-07-23 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['department__school', 'department', 'name'], 'permissions': [('can_manage_section', 'Can manage sections'), ('can_assign_mentor', 'Can assign mentor to section')], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to disable this section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
