# Generated by Django 5.2.4 on 2025-07-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_section_options_section_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
