# Generated by Django 5.2.4 on 2025-07-23 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_section_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-created_at'], 'verbose_name': 'File Upload', 'verbose_name_plural': 'File Uploads'},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
