# Generated by Django 5.2.4 on 2025-07-23 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_fileupload_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_sections', to='users.school'),
        ),
    ]
