# Generated by Django 5.2 on 2025-07-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_section_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About GSSC Portal', max_length=200)),
                ('content', models.TextField(help_text='Content for the about section. HTML tags are supported.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Content',
                'verbose_name_plural': 'About Content',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Excel File', 'verbose_name_plural': 'Excel Files Of Sections'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-created_at']},
        ),
    ]
