# Generated by Django 5.2 on 2026-02-10 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandler', '0008_alter_sheetcategory_options'),
        ('users', '0007_aboutcontent_alter_fileupload_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enrollment_no', models.CharField(max_length=64)),
                ('sgpa', models.CharField(blank=True, max_length=32)),
                ('cgpa', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excelhandler.excelfile')),
                ('source_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excelhandler.sheetcategory')),
            ],
            options={
                'verbose_name': 'Student Detail',
                'verbose_name_plural': 'Student Details',
                'ordering': ['mentor', 'enrollment_no'],
                'unique_together': {('mentor', 'enrollment_no')},
            },
        ),
    ]
