# Generated by Django 5.2.4 on 2025-07-20 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SheetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('year_range', models.CharField(max_length=50)),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_categories', to='excelhandler.excelfile')),
            ],
            options={
                'verbose_name_plural': 'Sheet categories',
            },
        ),
    ]
