# Generated by Django 5.2.4 on 2025-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetcategory',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional information about the sheet', null=True),
        ),
    ]
