# Generated by Django 5.2.4 on 2025-07-24 10:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandler', '0002_sheetcategory_comments'),
        ('users', '0006_section_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excel_files', to='users.department'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excel_files', to='users.school'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excel_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sheetcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sheetcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sheetcategory',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_categories', to='users.department'),
        ),
        migrations.AlterField(
            model_name='sheetcategory',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_categories', to='users.program'),
        ),
        migrations.AlterField(
            model_name='sheetcategory',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_categories', to='users.school'),
        ),
    ]
