# Generated by Django 5.2.4 on 2025-07-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('excelhandler', '0003_excelfile_department_excelfile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetcategory',
            name='school',
        ),
        migrations.RemoveField(
            model_name='sheetcategory',
            name='department',
        ),
        migrations.RemoveField(
            model_name='sheetcategory',
            name='program',
        ),
        migrations.AddField(
            model_name='sheetcategory',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_categories', to='users.school'),
        ),
        migrations.AddField(
            model_name='sheetcategory',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_categories', to='users.department'),
        ),
        migrations.AddField(
            model_name='sheetcategory',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_categories', to='users.program'),
        ),
    ]
