# Generated by Django 5.2.4 on 2025-07-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandler', '0004_auto_20250724_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetcategory',
            name='department_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sheetcategory',
            name='program_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sheetcategory',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
