# Generated by Django 5.2.4 on 2025-07-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandler', '0005_sheetcategory_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetcategory',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='sheetcategory',
            name='program_name',
        ),
        migrations.RemoveField(
            model_name='sheetcategory',
            name='school_name',
        ),
    ]
