# Generated by Django 5.2.4 on 2025-07-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandler', '0006_remove_sheetcategory_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetcategory',
            name='program',
            field=models.CharField(max_length=100),
        ),
    ]
