# Generated by Django 5.2 on 2026-02-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandler', '0007_alter_sheetcategory_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetcategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sheet Category', 'verbose_name_plural': 'Sheet Categories'},
        ),
    ]
